# Generated by Django 3.0.2 on 2020-01-24 15:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20190125_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photograph',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='categories/'),
            preserve_default=False,
        ),
    ]
